### ISSUE TITLE
Include full Uniform in app shell

### ISSUE THREAD

**Issue by warpech** [Polyjuice/SysUpgrade#102]
Right now, only Underwear part is included in app shell.

This has the following negative consequences:

- browser downloads both underwear.css and uniform.css for shadow roots, causing double-transfer of the uniform part
- browser downloads uniform.css at a later point, resulting in FOUC that can be mitigated with a verbose prefer have
- developers are complaining that they can't use uni-primary-button in a table
- our spirit should be to promote good practice of putting presentation in shadow root, but we should not force it because people will do crazy workarounds

I propose that we prefer have and load Uniform.css directly in the app shell.

@tomalec I'd like to hear your opinion on this

**Comment by tomalec** [comment]
I think we agreed on this sometime in July sprint on Uniform. For sure we talked about using it in content part (=> importing it at least in light DOM part of a view). But given we agreed to merge Underwear and Uniform together, I think it implies adding Uniform to app shell as well.

It's not 100% perfect solution, as it's somewhat intrusive, by preloading set of very opinionated CSS rules for every page and app. However, it can always get replaced with modified `app-shell.html`, or providing an app (StarcouterClientFiles) that overwrites `uniform.css` with something new (or empty) - hacky but doable. 

At least it gives good looking results from step 1 in app development and demos. I believe good DevX and UI is important enough to pay that price.

We just need to take care to keep uniform clean, not to bloat the page or introduce hard to overwrite selectors. Also, by separating some rules to inner styles of elements, we should slightly reduce this burden. Let's hope we will not implement the new Bootstrap with its problems we are actually trying to solve by Uniform.

**Comment by warpech** [comment]
Great, thanks! @alshakero can you pls implement this?
