### ISSUE TITLE
The build results do not notify GitHub properly

### ISSUE THREAD

**Issue by warpech** [Polyjuice/SysUpgrade#121]
For @tomalec's commit https://github.com/Starcounter/StarcounterClientFiles/pull/120/commits/9d2511af7c34b97126caa2e40737f88d9be7705d, the build was run and failed: https://teamcity.starcounter.org/viewLog.html?buildId=69056&tab=buildResultsDiv&buildTypeId=Apps_WebPlatform_StarcounterClientFiles_TestWithApps. 

The problem is that the result was not reported to GitHub. See:

<img width="1499" alt="screen shot 2018-09-21 at 13 38 39" src="https://user-images.githubusercontent.com/566463/45879145-acba2780-bda3-11e8-968f-b4cffc9eab00.png">

We should see red ticks in https://github.com/Starcounter/StarcounterClientFiles/pull/120

cc @tomalec

**Comment by ubbeK** [comment]
I selected `StarcounterClientFiles 3.x` as VCS root, hopefully that fixes this issue

Runnig builds:
* https://teamcity.starcounter.org/viewQueued.html?itemId=69232
* https://teamcity.starcounter.org/viewQueued.html?itemId=69230&tab=queuedBuildOverviewTab

**Comment by ubbeK** [comment]
I had to update our access token in the `commit status publiser` even though it worked through the `Test connection`-button.

Closing as fixed.
