### ISSUE TITLE
Add Underwear and Uniform to bower.json uninstall bootstrap

### ISSUE THREAD

**Issue by tomalec** [Polyjuice/SysUpgrade#31]
As you can see in https://github.com/Starcounter/StarcounterClientFiles/blob/1.x/src/StarcounterClientFiles/bower.json they are not installed. Also the file referenced in `app-shell.html` does not exist in underwear.css bower package.

**Comment by warpech** [comment]
Underwear and Uniform are in branch `3.x` of this app. Branches `1.x` and `2.x` are with Bootstrap.

But I agree that it has to be added to `bower.json` in the branch `3.x`, because it's not there at the moment.

**Comment by tomalec** [comment]
@warpech  Should uniform contain underwear? Currently, it does, but I think it breaks the principle of separating minimalistic common look from the opinionated framework.

**Comment by warpech** [comment]
Uniform should NOT contain Underwear.

There should be 2 demo pages:

- one without Underwear (for principle)
- anouther one with Underwear (for our convenience)

**Comment by tomalec** [comment]
This is done by #36
