### ISSUE TITLE
Update Polymer to 2.5

### ISSUE THREAD

**Issue by tomalec** [Polyjuice/SysUpgrade#37]
Currently I'm facing an issue with data-binding needed to finish https://github.com/Starcounter/KitchenSink/pull/241

The case seems to work with latest Polymer.

@warpech Do you think we can safely upgrade Polymer, or should I look for a workaround for 2.3.1?

**Comment by warpech** [comment]
If it fixes a real issue then let's do it.

Please make a PR for `3.x` and `2.x`. We will test it using https://github.com/Starcounter/AdminTrack/issues/435

**Comment by alshakero** [comment]
Done. 2.3.0 and 3.0.0-rc.4 are published everywhere.
