### ISSUE TITLE
Instructions in README and CONTRIBUTING are not aligned

### ISSUE THREAD

**Issue by warpech** [Polyjuice/SysUpgrade#67]
All instructions about releasing a version should be in CONTRIBUTING file, not distributed accross two files:

https://github.com/Starcounter/StarcounterClientFiles/blob/3.x/README.md
https://github.com/Starcounter/StarcounterClientFiles/blob/3.x/CONTRIBUTING.md

As found in https://github.com/Starcounter/StarcounterClientFiles/pull/64#issuecomment-381175880

**Comment by tomalec** [comment]
Do we have any update on that, as I'd like to release a new version today?

**Comment by alshakero** [comment]
PR in https://github.com/Starcounter/StarcounterClientFiles/pull/68

**Comment by alshakero** [comment]
So, the issue was actually covered in the proposed docs https://github.com/Starcounter/StarcounterClientFiles/blob/fix-docs/CONTRIBUTING.md#bumping-level1-to-use-the-new-version. Is this good to go?
