### ISSUE TITLE
Missleading, not used config and env vars for TC

### ISSUE THREAD

**Issue by tomalec** [Polyjuice/SysUpgrade#73]
It seems we have some config in TC that actually makes no effect, like `build.vcs.number.GitStarcounterClientFiles`, `env.GIT_CLIENTFILES_BRANCH` and maybe something more.

@ubbeK, @alshakero  Am I correct that those vars are not used, and only [nuget setup](https://github.com/Starcounter/level1/blob/def3b8f8036ed8c74305aa700e14611a6efd2539/src/BuildSystem/ClientFiles/ClientFiles.csproj) matters now?

It is confusing to have different places where you can set SCF version to be used for a build, while only one works.

**Comment by ubbeK** [comment]
> @ubbeK, @alshakero Am I correct that those vars are not used, and only nuget setup matters now?

Yes, but there was a bug in the old build environment. It has been updated so it actually includes the content from the nuget package instead from git source.

I will remove StarcounterClientFiles sources from the old TC build, including `build.vcs.number.GitStarcounterClientFiles`

**Comment by ubbeK** [comment]
> I will remove StarcounterClientFiles sources from the old TC build, including build.vcs.number.GitStarcounterClientFiles

Done!

**Comment by warpech** [comment]
@tomalec I assume this can this be closed now?
