### ISSUE TITLE
Update package.json

### ISSUE THREAD

**Issue by warpech** [Polyjuice/SysUpgrade#76]
For reasons enclosed on Slack: https://starcounter.slack.com/archives/C7677F70W/p1524776857000399

**Comment by warpech** [comment]
Same alert appears in 

- [ ] https://github.com/Starcounter/starcounter-layout-html-editor
- [ ] https://github.com/Starcounter/Blending
- [ ] https://github.com/Starcounter/starcounter-include
- [ ] https://github.com/Juicy/juicy-popover
- [ ] Perhaps few more Juicy and Palindrom repos?

**Comment by alshakero** [comment]
It will appear wherever Polymer 2.0 appears.

**Comment by alshakero** [comment]
Closing as it's a false flag, see https://github.com/request/request/issues/2926#issuecomment-384853637

Extra assurance from a GH staffer: https://github.com/hapijs/hoek/issues/247#issuecomment-386708295

**Comment by alshakero** [comment]
Reopening as 2.16.3 is indeed infected. The false flag was for 4.2.1.

**Comment by warpech** [comment]
This is not urgent, moving to July.

**Comment by warpech** [comment]
Web Components Tester 6.7.0 was released this week. I suppose it might fix the vulnerabilities alerts: https://github.com/Polymer/tools/releases/tag/web-component-tester%406.7.0

Edit: it might not be enough, given this PR that was started afterwards: https://github.com/Polymer/tools/pull/533

**Comment by alshakero** [comment]
Polymer/tools#533 is still WIP

**Comment by warpech** [comment]
Meanwhile, I can see that some of our vulnerabilities actually don't depend on it:

- the vulnerability in https://github.com/Palindrom/Palindrom seems to be in our control by upgrading Mocha to the current version

**Comment by alshakero** [comment]
> the vulnerability in Palindrom/Palindrom seems to be in our control by upgrading Mocha to the current version

PR in https://github.com/Palindrom/Palindrom/pull/213

**Comment by warpech** [comment]
There is a general solution that should be applied in all affected repos that have `web-component-tester` in `package.json`: https://github.com/Starcounter/starcounter-include/pull/106

@alshakero could you pls apply it in all relevant repos?

**Comment by warpech** [comment]
What's the status of this?

**Comment by alshakero** [comment]
It is blocked by this https://github.com/Palindrom/Palindrom/pull/213

**Comment by warpech** [comment]
Meanwhile, can you look at other custom element repos, such as https://github.com/Starcounter/starcounter-layout-html-editor?

**Comment by alshakero** [comment]
https://github.com/Starcounter/starcounter-layout-html-editor is fixed.

**Comment by alshakero** [comment]
Closing as finally done. I think all security warnings are fixed at this point except Blending's one which should be fixed here https://github.com/Starcounter/Blending/pull/277.

Are you aware of any other security warnings?

**Comment by warpech** [comment]
Do you have "Vulnerability alerts" subscribed on the page https://github.com/settings/notifications?

Every day I get a daily digest with the repos that still have vulnerabilities. Today's report includes:

- https://github.com/Palindrom/puppetjs.github.io
- https://github.com/Palindrom/palindrom.github.io
- https://github.com/Juicy/juicy.github.io
- https://github.com/Starcounter/SignIn - this can be fixed by @Mihaiii if you say how to fix that
- https://github.com/Starcounter/People - this can be fixed by @Mihaiii if you say how to fix that
- https://github.com/Starcounter/Blending - this can be fixed by @PatrykSzwer if you say how to fix that

**Comment by alshakero** [comment]
> Do you have "Vulnerability alerts" subscribed on the page github.com/settings/notifications?

Now I do.

Blending should be fixed by this PR https://github.com/Starcounter/Blending/pull/277

**Comment by alshakero** [comment]
1. Palindrom/puppetjs.github.io, I archived the repo.
2. Palindrom/palindrom.github.io, **Fixed**
3. Juicy/juicy.github.io, ~~working on it~~. **Fixed**.
4. Starcounter/SignIn, ~~tracked [here](https://github.com/Starcounter/SignIn/issues/165)~~ **Fixed**.
5. Starcounter/People, ~PR [here](https://github.com/Starcounter/People/pull/177)~. **Fixed**.
6. Starcounter/Blending ~PR [here](https://github.com/Starcounter/Blending/pull/277)~. **Fixed**.

**Comment by alshakero** [comment]
Closing as all fixed.

**Comment by warpech** [comment]
Huge victory! Thanks everyone involved

![](https://media.giphy.com/media/tnmZ0JCjoyOxG/giphy.gif)
