### ISSUE TITLE
Release instructions are redundand and tangled with warehouse publishing

### ISSUE THREAD

**Issue by tomalec** [Polyjuice/SysUpgrade#79]
https://github.com/Starcounter/StarcounterClientFiles/blob/3.x/CONTRIBUTING.md#releasing-of-a-new-version-of-starcounterclientfiles-3x

Points 7-9:
> 7. Still in the feature branch, push a tag (3.x.y), and add release notes to GitHub release of StarcounterClientFiles.
> 8. Still in the feature branch, publish a package of this version to App Warehouse (built with Starcounter 2.4). You may follow the steps to do this [here](https://github.com/Starcounter/CompanyTrack/blob/master/AppsTeam/Guidelines/releasing-to-warehouse.md). 
> 9. Execute [package.bat](https://github.com/Starcounter/StarcounterClientFiles/blob/3.x/package.bat)
    * this will create a nuget package of StarcounterClientFiles called `Starcounter.ClientFiles` to folder `/StarcounterClientFiles/artifacts/Starcounter.ClientFiles.X.Y.Z.nupkg`

Are same as few of https://github.com/Starcounter/CompanyTrack/blob/master/AppsTeam/Guidelines/releasing-to-warehouse.md
but in different order, what makes it confusing to follow such an algorithm.

I think (but I'm not sure, @alshakero please correct me if I'm wrong) we need something like:

> 7. Still in the feature branch, bump assembly version, publish a package of this version to App Warehouse (built with Starcounter 2.4), and release to GitHub. You may follow the steps to do this [here](https://github.com/Starcounter/CompanyTrack/blob/master/AppsTeam/Guidelines/releasing-to-warehouse.md). 
    * [package.bat](https://github.com/Starcounter/StarcounterClientFiles/blob/3.x/package.bat) will create a nuget package of StarcounterClientFiles called `Starcounter.ClientFiles` to folder `/StarcounterClientFiles/artifacts/Starcounter.ClientFiles.X.Y.Z.nupkg`

-----

BTW, I think most of GH & warehouse releasing and package building could/should be automated. Bellow 8 points seems more-or-less what we do in our clinet-side packages with `grunt bump:minor`

> 2. Open the solution file `.sln` in Visual Studio
> 3. Go to `AssemblyInfo.cs` under `Properties`
> 4. Increment `AssemblyVersion` and `AssemblyFileVersion` according to [semver](http://semver.org/) as described [below](#SEMVER). For example, to make a change that introduces new functionality, the second number should be incremented. As such, this:
>    ```cs
>    [assembly: AssemblyVersion("1.0.0")]
>    [assembly: AssemblyFileVersion("1.0.0")]
>    ```
>    Should turn into this:
>    ```cs
>    [assembly: AssemblyVersion("1.1.0")]
>    [assembly: AssemblyFileVersion("1.1.0")]
>    ```
> 5. Build the solution using Visual Studio, running `build.bat`, or `./build.bat` in Git Bash)
> 6. Package the solution by running `package.bat` or `./package.bat` in Git Bash
> 7. x
> 8. Commit the incremented version with a message identical to the version:
>    ```git
>    git add -u // -u flag to ensure that the zip is not included
>    git commit -m "1.1.0" //the version number
>    ```
>9. Add a tag to the commit:
>    ```git
>    git tag -a "1.1.0" -m "1.1.0"
>    ```
>10. Push the changes:
>    ```git
>    git push && git push --tags
>     ```

@alshakero, @warpech, @PatrykSzwer, @kegor WDYT?

**Comment by warpech** [comment]
Thank you @tomalec. These are two completely different questions in one issue. Let's deal with the first part of it fast.

@alshakero if you agree with @tomalec's proposal:

> 7. Still in the feature branch, bump assembly version, publish a package of this version to App Warehouse (built with Starcounter 2.4), and release to GitHub. You may follow the steps to do this [here](https://github.com/Starcounter/CompanyTrack/blob/master/AppsTeam/Guidelines/releasing-to-warehouse.md). 
    * [package.bat](https://github.com/Starcounter/StarcounterClientFiles/blob/3.x/package.bat) will create a nuget package of StarcounterClientFiles called `Starcounter.ClientFiles` to folder `/StarcounterClientFiles/artifacts/Starcounter.ClientFiles.X.Y.Z.nupkg`

Please make a PR for that change.

----

Regarding app packaging automation, I don't have opinion other than https://xkcd.com/1205/. @alshakero if you consider automating releasing would save you time, please make a new issue for that.

**Comment by alshakero** [comment]
Releasing is taking me 10 mins now. I measured it last time. Should I automate?

**Comment by alshakero** [comment]
This was fixed in https://github.com/Starcounter/StarcounterClientFiles/pull/68. I verified but would appreciate a quick skim to make sure I understand correctly. It's worth mentioning that I do remember that this issue was a duplicate since it was created. 

Please close if it was indeed addressed.

**Comment by warpech** [comment]
> Releasing is taking me 10 mins now. I measured it last time. Should I automate?

Partial automation of something that takes 10 minutes once every 2 weeks does not sound like a good use of our time.

**Comment by warpech** [comment]
@alshakero Tomek approved PR #68 on April 24th and then it was merged.

This issue was created by Tomek on May 9th so how could it be addressed in PR #68?

**Comment by alshakero** [comment]
@warpech you're right, sorry.
