### ISSUE TITLE
Build warning Known moderate severity security vulnerability detected in hoek < 4.2.1 defined in package

### ISSUE THREAD

**Issue by LarsTjernstrom** [Polyjuice/SysUpgrade#80]
2018-05-04 Lars Tjernström
I receive these the warning below. Can someone please upgrade **hoek** version to greater then 4.2.1 to get rid of these warnings?

Starcounter/StarcounterClientFiles

Known moderate severity security vulnerability detected in hoek < 4.2.1 defined in package-lock.json.package-lock.json update suggested: hoek ~> 4.2.1.Always verify the validity and compatibility of suggestions with your codebase. | Known moderate severity security vulnerability detected in hoek < 4.2.1 defined in package-lock.json. | package-lock.json update suggested: hoek ~> 4.2.1. | Always verify the validity and compatibility of suggestions with your codebase.
Known moderate severity security vulnerability detected in hoek < 4.2.1 defined in package-lock.json.
package-lock.json update suggested: hoek ~> 4.2.1.
Always verify the validity and compatibility of suggestions with your codebase.

**Comment by alshakero** [comment]
Hi, yes I'm preparing a PR for the lib that uses hoek. It's [`request`](https://github.com/request/request). `request` is used inside `selenium-standalone` which we use in `web-component-tester`.

**Comment by alshakero** [comment]
Update: It's already discussed and it's a false flag, see https://github.com/request/request/issues/2926#issuecomment-384853637

**Comment by alshakero** [comment]
Closing as duplicate of #76
